FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --production

COPY . .

EXPOSE 8000

ENV PORT=8000
ENV MONGO_INITDB_ROOT_USERNAME=tranquocviet1303
ENV MONGO_INITDB_ROOT_PASSWORD=PoO8kyX0uPa23ICU
ENV MONGO_HOST=maincluster.hc46h.mongodb.net
ENV MONGO_APP_NAME=MainCluster
ENV MONGO_URI=mongodb+srv://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST}/?retryWrites=true&w=majority&appName=${MONGO_APP_NAME}
ENV REDIS_HOST=localhost
ENV REDIS_PORT=6379
ENV JWT_SECRET=ZtmooArsycOD6olPEPrE78U0H9XTJolL
ENV JWT_EXPIRE_IN=60
ENV JWT_REFRESH_SECRET=XG9DuXcPTbJl1cjTU4kmHD3m68Fqm6s2
ENV JWT_REFRESH_EXPIRE_IN=120

CMD ["yarn", "start:prod"]
