version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: local_redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWPRD=${REDIS_PASSWPRD}
    volumes:
      - redis_data:/data

volumes:
  redis_data: